### ISSUE TITLE
driver cannot connect to cluster port

### ISSUE THREAD

**Issue by j-larson** [jdbc-json/jdbc-cb#18]
Setting the port number in the connection URL to 8091 (the cluster admin port) instead of 8093 (the direct query port) should work. It doesn't.

05:23:36.144 [main] INFO  com.couchbase.CBDriver - Constructor called
05:23:36.148 [main] INFO  com.couchbase.CBDriver - Constructor called
05:23:36.433 [main] ERROR com.couchbase.jdbc.core.ProtocolImpl - Error opening connection Not found: Check the URL: 404
05:23:36.434 [main] ERROR com.couchbase.CBConnection - Error opening connection for jdbc:couchbase://localhost:8091 exception Error getting cluster response
Exception in thread "main" java.sql.SQLException: Error opening connection
    at com.couchbase.CBConnection.<init>(CBConnection.java:79)
    at com.couchbase.CBDriver.connect(CBDriver.java:95)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)
    at com.couchbase.query.jdbc.SimpleExec.main(SimpleExec.java:12)
Caused by: org.apache.http.client.ClientProtocolException: Not found: Check the URL: 404
    at com.couchbase.jdbc.core.ProtocolImpl.handleClusterResponse(ProtocolImpl.java:286)
    at com.couchbase.jdbc.core.ProtocolImpl.pollCluster(ProtocolImpl.java:944)
    at com.couchbase.jdbc.core.ProtocolImpl.connect(ProtocolImpl.java:235)
    at com.couchbase.CBConnection.<init>(CBConnection.java:73)
    ... 4 more

Repro using this:

package com.couchbase.query.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class SimpleExec {
    static String ConnectionURL = "jdbc:couchbase://localhost:8091";

```
public static void main(String[] args) throws Exception {
    Connection con = DriverManager.getConnection(ConnectionURL);
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("select code,* from `beer-sample` where city = 'San Francisco' and type = 'brewery'");
    while (rs.next()) {
        String val = rs.getString(1);
        String code = rs.getString(2);
        System.out.println("> " + val);
        System.out.println(">> " + code);
    }
}
```

}

**Comment by j-larson** [comment]
Basically, pointing the driver to the 8091 general administration port, is the wrong thing to do. The driver should be pointed to the 8093 query port. It then uses a special REST API to get the list of query nodes, and thereafter round-robins its requests across them.
