### ISSUE TITLE
 testNestedOperator fails,getSQLJSON method not returning results for nested maps

### ISSUE THREAD

**Issue by j-larson** [jdbc-json/jdbc-cb#27]
Originally https://issues.couchbase.com/browse/MB-18257 .

Created a nested map as:
JSONObject nestedobj = new JSONObject();
HashMap<String, Object> map = new HashMap<String, Object>();
nestedobj.put("nested.nested", "1");
map.put("name", "test_name");
map.put("specialchars", "()_&^%$!@{}{}:\"\\';::");
map.put("id", 12345);
map.put("double", 12345.333);
map.put("data_time", "2001-01-01 01:01:01.00");
obj.put("nested", nestedobj);
obj.putAll(map);
Object gets inserted correctly using:
HashMap<String,JSONObject> objMap = new HashMap<String,JSONObject>();
objMap.put("1_testNestedOperator", obj);
JDBCTestUtils.insertData(objMap, "default");
Document 1_testNestedOperator seen in UI correctly.
Try to retrieve using following query:
String query = "select default.nested._ from default";
JDBCTestUtils.resetConnection();
try ( Connection con = JDBCTestUtils.con)
{
try (Statement stmt = con.createStatement())
{
try (ResultSet rs = stmt.executeQuery(query))
{
while(rs.next()){
CBResultSet cbrs = (CBResultSet) rs;
java.sql.ResultSetMetaData meta = cbrs.getMetaData();
SQLJSON jsonVal1 = cbrs.getSQLJSON("nested");*
Above line gives error:
*java.sql.SQLException: ResultSet does not contain nested *
at com.couchbase.CBResultSet.checkColumnLabelMissing(CBResultSet.java:5758)
at com.couchbase.CBResultSet.getSQLJSONChecked(CBResultSet.java:1618)
at com.couchbase.CBResultSet.getSQLJSON(CBResultSet.java:1611)
at com.couchbase.ProjectionJDBCDriverTests.testNestedOperator(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by j-larson** [comment]
String query = "select default.nested.\* from default";

**Comment by j-larson** [comment]
Fixed by pull request https://github.com/jdbc-json/jdbc-cb/pull/19 .
