### ISSUE TITLE
testSeriesOfObjectsWithSimilarFields failure

### ISSUE THREAD

**Issue by pm48** [jdbc-json/jdbc-cb#28]
Insert 2 objects with similar fields:
HashMap<String, Object> map = new HashMap<String, Object>();
        map.put("name", "test_name");
        map.put("id", 12345);
        JSONObject nestedObject1 = new JSONObject();
        JSONObject nestedObject2  = new JSONObject();
        nestedObject1.put("nest_field_name_1", "test_nest_1");
        nestedObject1.put("nest_field_id_1", 1);
        nestedObject2.put("nest_field_name_2", "test_nest_2");
        nestedObject2.put("nest_field_id_2", 2);
        JSONArray expectedArray = new JSONArray();
        obj.put("nested_data_1", nestedObject1);
        obj.put("nested_data_2", nestedObject2);
        obj.putAll(map);

When trying to retrieve the data as:
String query = "select default.nested_data_2.\* , default.nested_data_1.\*  from default";
Resultset returned is not in a consistent order.
Hence test fails against comparison of returned dataset.

**Comment by pm48** [comment]
This test still fails with:
testSeriesOfObjectsWithSimilarFields(com.couchbase.jdbc.ProjectionJDBCDriverTests)  Time elapsed: 30.214 sec  <<< ERROR!
java.sql.SQLException: value test_nest_1 not a number
    at com.couchbase.jdbc.core.SqlJsonImplementation.getInt(SqlJsonImplementation.java:254)
    at com.couchbase.jdbc.ProjectionJDBCDriverTests.testSeriesOfObjectsWithSimilarFields(ProjectionJDBCDriverTests.java:465)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
