### ISSUE TITLE
Not able to connect to any other machine through jdbc-json driver

### ISSUE THREAD

**Issue by pm48** [jdbc-json/jdbc-cb#42]
I tried an example with beer-sample and travel-sample on localhost and it worked fine.
But when I tried same with a different hostname:
static String ConnectionURL = "jdbc:couchbase://172.23.107.107:8093";

I get this error:
9:51:35.463 [main] ERROR com.couchbase.CBConnection - Error opening connection for jdbc:couchbase://172.23.107.107:8091 exception Error getting cluster response
Exception in thread "main" java.sql.SQLException: Error opening connection
    at com.couchbase.CBConnection.<init>(CBConnection.java:79)
    at com.couchbase.CBDriver.connect(CBDriver.java:95)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)
    at com.test.jdbc2.test.App.main(App.java:17)
Caused by: org.apache.http.client.ClientProtocolException: Not found: Check the URL: 404
    at com.couchbase.jdbc.core.ProtocolImpl.handleClusterResponse(ProtocolImpl.java:286)
    at com.couchbase.jdbc.core.ProtocolImpl.pollCluster(ProtocolImpl.java:944)
    at com.couchbase.jdbc.core.ProtocolImpl.connect(ProtocolImpl.java:235)
    at com.couchbase.CBConnection.<init>(CBConnection.java:73)
    ... 4 more

**Comment by j-larson** [comment]
This sounds a lot like issue #33, which is fixed, but the fix has not yet been uploaded. Did you try with the locally-built version?
