### ISSUE TITLE
Get Invalid Index and NullPointerException with simple query

### ISSUE THREAD

**Issue by davidmichaelkarr** [jdbc-json/jdbc-cb#58]
I'm using the latest couchbase community edition and the latest version of this jdbc driver.

I created a cluster and a bunch of buckets, and I created a primary index on one of the buckets.

I connected to the database from SQuirreL, using this JDBC driver.  I tried to run a simple query with just "select * from bucketName where <checking one column value>".  It failed, and I saw the following in the log:

`2018-02-21 11:50:49,185 [Thread-3] INFO  net.sourceforge.squirrel_sql.fw.util.log.SystemOutToLog  - 11:50:49.184 [Thread-3] DEBUG com.couchbase.jdbc.CBResultSet - Loaded result set
2018-02-21 11:50:49,185 [Thread-3] ERROR net.sourceforge.squirrel_sql.client.session.schemainfo.SchemaInfoCache  - Could not get table types
java.sql.SQLException: Invalid index
	at com.couchbase.jdbc.CBResultSet.checkIndex(CBResultSet.java:5737)
	at com.couchbase.jdbc.CBResultSet.getString(CBResultSet.java:178)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDatabaseMetaData.getTableTypes(SQLDatabaseMetaData.java:828)
2018-02-21 11:50:51,225 [Thread-3] ERROR net.sourceforge.squirrel_sql.client.session.schemainfo.SchemaInfo  - failed to load table names
java.lang.NullPointerException
	at com.couchbase.jdbc.core.ProtocolImpl.handleResponse(ProtocolImpl.java:483)
	at com.couchbase.jdbc.core.ProtocolImpl.query(ProtocolImpl.java:366)
	at com.couchbase.jdbc.CBStatement.executeQuery(CBStatement.java:75)
	at com.couchbase.jdbc.CBDatabaseMetaData.getTables(CBDatabaseMetaData.java:1850)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDatabaseMetaData.getTables(SQLDatabaseMetaData.java:993)
2018-02-21 11:50:55,195 [Thread-2] INFO  net.sourceforge.squirrel_sql.fw.util.log.SystemOutToLog  - 11:50:55.195 [Thread-2] ERROR com.couchbase.jdbc.core.ProtocolImpl - Error executing query [select * from ONEMAP_PLACES where tz = "pst"
2018-02-21 11:50:55,196 [Thread-2] INFO  net.sourceforge.squirrel_sql.fw.util.log.SystemOutToLog  - limit 10] User does not have credentials to run SELECT queries on the ONEMAP_PLACES bucket. Add role query_select on ONEMAP_PLACES to allow the query to run.`

I double-checked the user that I'm connecting to cb with, and its roles, and it has query access to all of the buckets.

**Comment by j-larson** [comment]
Thanks for the problem report. I will investigate.

To work around the problem, try accessing using admin credentials. Credentials are set like this:
https://github.com/jdbc-json/jdbc-cb/blob/master/examples/UseCredentials.java
